<a href="https://colab.research.google.com/github/Harshgadre/harsh/blob/main/02_India_Agriculture_Crop_Production.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/11_Projects/Copy of India Agriculture Crop Production.csv')
df.head()

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,Hectare,2061.0,Tonnes,1.643541
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.655803
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.209358
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.0,Hectare,5239.0,Tonnes,1.690000
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.696296

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345407 entries, 0 to 345406
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345407 non-null  object
 1   District          345407 non-null  object
 2   Crop              345375 non-null  object
 3   Year              345407 non-null  object
 4   Season            345406 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345407 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345407 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 26.4+ MB

# Unique count and values for Crops,Districts

In [ ]:
unique_crop_list = df['Crop'].unique()

In [ ]:
print(f'Total number of unique crops in India is {len(unique_crop_list)}\nThey are \n {unique_crop_list}')

Total number of unique crops in India is 57
They are
 ['Arecanut' 'Banana' 'Black pepper' 'Cashewnut' 'Coconut' 'Dry chillies'
 'Ginger' 'Other Kharif pulses' 'other oilseeds' 'Rice' 'Sugarcane'
 'Sweet potato' 'Arhar/Tur' 'Bajra' 'Castor seed' 'Coriander'
 'Cotton(lint)' 'Gram' 'Groundnut' 'Horse-gram' 'Jowar' 'Linseed' 'Maize'
 'Mesta' 'Moong(Green Gram)' 'Niger seed' 'Onion' 'Other Rabi pulses'
 'Potato' 'Ragi' 'Rapeseed &Mustard' 'Safflower' 'Sesamum' 'Small millets'
 'Soyabean' 'Sunflower' 'Tapioca' 'Tobacco' 'Turmeric' 'Urad' 'Wheat'
 'Oilseeds total' 'Jute' 'Masoor' 'Peas & beans (Pulses)' 'Barley'
 'Garlic' 'Khesari' 'Sannhamp' 'Guar seed' 'Moth' 'Cardamom'
 'Other Cereals' 'Cowpea(Lobia)' 'Dry Ginger' 'Other Summer Pulses' nan]

In [ ]:
unique_district_list = df['District'].unique()
print(f'Total number of District in India is {len(unique_district_list)}\nThey are: \n {unique_district_list}')

Total number of District in India is 729
They are:
 ['NICOBARS' 'NORTH AND MIDDLE ANDAMAN' 'SOUTH ANDAMANS' 'ANANTAPUR'
 'EAST GODAVARI' 'KRISHNA' 'VIZIANAGARAM' 'WEST GODAVARI' 'ADILABAD'
 'CHITTOOR' 'GUNTUR' 'KADAPA' 'KARIMNAGAR' 'KHAMMAM' 'KURNOOL'
 'MAHBUBNAGAR' 'MEDAK' 'NALGONDA' 'NIZAMABAD' 'PRAKASAM' 'RANGAREDDI'
 'SPSR NELLORE' 'SRIKAKULAM' 'VISAKHAPATANAM' 'WARANGAL' 'CHANGLANG'
 'DIBANG VALLEY' 'EAST KAMENG' 'EAST SIANG' 'KURUNG KUMEY' 'LOHIT'
 'LOWER DIBANG VALLEY' 'LOWER SUBANSIRI' 'PAPUM PARE' 'TAWANG' 'TIRAP'
 'UPPER SIANG' 'UPPER SUBANSIRI' 'WEST KAMENG' 'WEST SIANG' 'BARPETA'
 'BONGAIGAON' 'CACHAR' 'DARRANG' 'DHEMAJI' 'DHUBRI' 'DIBRUGARH'
 'DIMA HASAO' 'GOALPARA' 'GOLAGHAT' 'HAILAKANDI' 'JORHAT' 'KAMRUP'
 'KARBI ANGLONG' 'KARIMGANJ' 'KOKRAJHAR' 'LAKHIMPUR' 'MARIGAON' 'NAGAON'
 'NALBARI' 'SIVASAGAR' 'SONITPUR' 'TINSUKIA' 'ARARIA' 'ARWAL' 'AURANGABAD'
 'BANKA' 'BEGUSARAI' 'BHAGALPUR' 'BHOJPUR' 'BUXAR' 'DARBHANGA' 'GAYA'
 'GOPALGANJ' 'JAMUI' 'JEHANABAD' 'KAIMUR (BHABUA)' 'KATIHAR' 'KHAGARIA'
 'KISHANGANJ' 'LAKHISARAI' 'MADHEPURA' 'MADHUBANI' 'MUNGER' 'MUZAFFARPUR'
 'NALANDA' 'NAWADA' 'PASHCHIM CHAMPARAN' 'PATNA' 'PURBI CHAMPARAN'
 'PURNIA' 'ROHTAS' 'SAHARSA' 'SAMASTIPUR' 'SARAN' 'SHEIKHPURA' 'SHEOHAR'
 'SITAMARHI' 'SIWAN' 'SUPAUL' 'VAISHALI' 'CHANDIGARH' 'BASTAR' 'BILASPUR'
 'DANTEWADA' 'DHAMTARI' 'DURG' 'JANJGIR-CHAMPA' 'JASHPUR' 'KABIRDHAM'
 'KANKER' 'KORBA' 'KOREA' 'MAHASAMUND' 'RAIGARH' 'RAIPUR' 'RAJNANDGAON'
 'SURGUJA' 'DADRA AND NAGAR HAVELI' 'Daman and Diu' 'Delhi' 'Goa'
 'AHMADABAD' 'AMRELI' 'ANAND' 'BANAS KANTHA' 'BHARUCH' 'BHAVNAGAR' 'DANG'
 'DOHAD' 'GANDHINAGAR' 'JAMNAGAR' 'JUNAGADH' 'KACHCHH' 'KHEDA' 'MAHESANA'
 'NARMADA' 'NAVSARI' 'PANCH MAHALS' 'PATAN' 'PORBANDAR' 'RAJKOT'
 'SABAR KANTHA' 'SURAT' 'SURENDRANAGAR' 'VADODARA' 'VALSAD' 'AMBALA'
 'BHIWANI' 'FARIDABAD' 'FATEHABAD' 'GURGAON' 'HISAR' 'JHAJJAR' 'JIND'
 'KAITHAL' 'KARNAL' 'KURUKSHETRA' 'MAHENDRAGARH' 'PANCHKULA' 'PANIPAT'
 'REWARI' 'ROHTAK' 'SIRSA' 'SONIPAT' 'YAMUNANAGAR' 'KANGRA' 'KULLU'
 'MANDI' 'SHIMLA' 'SOLAN' 'UNA' 'CHAMBA' 'HAMIRPUR' 'SIRMAUR' 'KINNAUR'
 'LAHUL AND SPITI' 'DODA' 'JAMMU' 'KATHUA' 'RAJAURI' 'UDHAMPUR' 'KARGIL'
 'LEH LADAKH' 'SRINAGAR' 'BADGAM' 'BARAMULLA' 'POONCH' 'PULWAMA'
 'ANANTNAG' 'KUPWARA' 'CHATRA' 'DUMKA' 'GARHWA' 'GODDA' 'GUMLA'
 'HAZARIBAGH' 'KODERMA' 'LATEHAR' 'LOHARDAGA' 'PAKUR' 'PALAMU' 'RANCHI'
 'SAHEBGANJ' 'SARAIKELA KHARSAWAN' 'SIMDEGA' 'WEST SINGHBHUM' 'BOKARO'
 'DEOGHAR' 'DHANBAD' 'EAST SINGHBUM' 'GIRIDIH' 'JAMTARA' 'BAGALKOT'
 'BANGALORE RURAL' 'BELGAUM' 'BELLARY' 'BENGALURU URBAN' 'CHAMARAJANAGAR'
 'CHIKMAGALUR' 'CHITRADURGA' 'DAKSHIN KANNAD' 'DAVANGERE' 'DHARWAD'
 'GADAG' 'HASSAN' 'HAVERI' 'KODAGU' 'KOLAR' 'MANDYA' 'MYSORE' 'SHIMOGA'
 'TUMKUR' 'UDUPI' 'UTTAR KANNAD' 'BIDAR' 'BIJAPUR' 'GULBARGA' 'KOPPAL'
 'RAICHUR' 'ALAPPUZHA' 'ERNAKULAM' 'IDUKKI' 'KANNUR' 'KASARAGOD' 'KOLLAM'
 'KOTTAYAM' 'KOZHIKODE' 'MALAPPURAM' 'PALAKKAD' 'PATHANAMTHITTA'
 'THIRUVANANTHAPURAM' 'THRISSUR' 'WAYANAD' 'ANUPPUR' 'ASHOKNAGAR'
 'BALAGHAT' 'BARWANI' 'BETUL' 'BHIND' 'BHOPAL' 'BURHANPUR' 'CHHATARPUR'
 'CHHINDWARA' 'DAMOH' 'DATIA' 'DEWAS' 'DHAR' 'DINDORI' 'GUNA' 'GWALIOR'
 'HARDA' 'HOSHANGABAD' 'INDORE' 'JABALPUR' 'JHABUA' 'KATNI' 'KHANDWA'
 'KHARGONE' 'MANDLA' 'MANDSAUR' 'MORENA' 'NARSINGHPUR' 'NEEMUCH' 'PANNA'
 'RAISEN' 'RAJGARH' 'RATLAM' 'REWA' 'SAGAR' 'SATNA' 'SEHORE' 'SEONI'
 'SHAHDOL' 'SHAJAPUR' 'SHEOPUR' 'SHIVPURI' 'SIDHI' 'TIKAMGARH' 'UJJAIN'
 'UMARIA' 'VIDISHA' 'AHMEDNAGAR' 'AKOLA' 'AMRAVATI' 'BEED' 'BHANDARA'
 'BULDHANA' 'CHANDRAPUR' 'DHULE' 'GADCHIROLI' 'GONDIA' 'HINGOLI' 'JALGAON'
 'JALNA' 'KOLHAPUR' 'LATUR' 'NAGPUR' 'NANDED' 'NANDURBAR' 'NASHIK'
 'OSMANABAD' 'PARBHANI' 'PUNE' 'RAIGAD' 'RATNAGIRI' 'SANGLI' 'SATARA'
 'SOLAPUR' 'THANE' 'WARDHA' 'WASHIM' 'YAVATMAL' 'SINDHUDURG' 'SENAPATI'
 'BISHNUPUR' 'CHANDEL' 'CHURACHANDPUR' 'IMPHAL EAST' 'IMPHAL WEST'
 'TAMENGLONG' 'THOUBAL' 'UKHRUL' 'EAST GARO HILLS' 'EAST JAINTIA HILLS'
 'EAST KHASI HILLS' 'RI BHOI' 'SOUTH GARO HILLS' 'WEST GARO HILLS'
 'WEST KHASI HILLS' 'AIZAWL' 'CHAMPHAI' 'KOLASIB' 'LUNGLEI' 'MAMIT'
 'SAIHA' 'DIMAPUR' 'KOHIMA' 'MOKOKCHUNG' 'MON' 'PHEK' 'TUENSANG' 'WOKHA'
 'ZUNHEBOTO' 'ANUGUL' 'BALANGIR' 'BALESHWAR' 'BARGARH' 'BHADRAK' 'BOUDH'
 'CUTTACK' 'DEOGARH' 'DHENKANAL' 'GAJAPATI' 'GANJAM' 'JAGATSINGHAPUR'
 'JAJAPUR' 'JHARSUGUDA' 'KALAHANDI' 'KANDHAMAL' 'KENDRAPARA' 'KENDUJHAR'
 'KHORDHA' 'KORAPUT' 'MALKANGIRI' 'MAYURBHANJ' 'NABARANGPUR' 'NAYAGARH'
 'NUAPADA' 'RAYAGADA' 'SAMBALPUR' 'SONEPUR' 'SUNDARGARH' 'PURI' 'MAHE'
 'PONDICHERRY' 'KARAIKAL' 'YANAM' 'AMRITSAR' 'BATHINDA' 'FARIDKOT'
 'FATEHGARH SAHIB' 'FIROZEPUR' 'HOSHIARPUR' 'JALANDHAR' 'KAPURTHALA'
 'LUDHIANA' 'MOGA' 'MUKTSAR' 'NAWANSHAHR' 'PATIALA' 'RUPNAGAR' 'SANGRUR'
 'MANSA' 'GURDASPUR' 'AJMER' 'ALWAR' 'BANSWARA' 'BARAN' 'BHARATPUR'
 'BHILWARA' 'BIKANER' 'BUNDI' 'CHITTORGARH' 'DAUSA' 'DHOLPUR' 'DUNGARPUR'
 'GANGANAGAR' 'HANUMANGARH' 'JAIPUR' 'JAISALMER' 'JALORE' 'JHALAWAR'
 'KARAULI' 'KOTA' 'NAGAUR' 'PALI' 'RAJSAMAND' 'SAWAI MADHOPUR' 'SIKAR'
 'SIROHI' 'TONK' 'UDAIPUR' 'BARMER' 'CHURU' 'JHUNJHUNU' 'JODHPUR'
 'PRATAPGARH' 'EAST DISTRICT' 'NORTH DISTRICT' 'SOUTH DISTRICT'
 'WEST DISTRICT' 'COIMBATORE' 'DHARMAPURI' 'DINDIGUL' 'ERODE'
 'KANNIYAKUMARI' 'KARUR' 'KRISHNAGIRI' 'NAGAPATTINAM' 'NAMAKKAL'
 'PERAMBALUR' 'SALEM' 'THANJAVUR' 'THE NILGIRIS' 'THENI' 'THIRUVARUR'
 'TIRUCHIRAPPALLI' 'TIRUNELVELI' 'VIRUDHUNAGAR' 'CUDDALORE' 'KANCHIPURAM'
 'MADURAI' 'PUDUKKOTTAI' 'RAMANATHAPURAM' 'SIVAGANGA' 'THIRUVALLUR'
 'THOOTHUKUDI' 'TIRUVANNAMALAI' 'VELLORE' 'VILLUPURAM' 'DHALAI'
 'NORTH TRIPURA' 'SOUTH TRIPURA' 'WEST TRIPURA' 'AGRA' 'ALIGARH'
 'ALLAHABAD' 'AMBEDKAR NAGAR' 'AMROHA' 'AURAIYA' 'AZAMGARH' 'BAGHPAT'
 'BAHRAICH' 'BALLIA' 'BALRAMPUR' 'BANDA' 'BARABANKI' 'BAREILLY' 'BASTI'
 'BIJNOR' 'BUDAUN' 'BULANDSHAHR' 'CHANDAULI' 'CHITRAKOOT' 'DEORIA' 'ETAH'
 'ETAWAH' 'FAIZABAD' 'FARRUKHABAD' 'FATEHPUR' 'FIROZABAD'
 'GAUTAM BUDDHA NAGAR' 'GHAZIABAD' 'GHAZIPUR' 'GONDA' 'GORAKHPUR' 'HARDOI'
 'HATHRAS' 'JALAUN' 'JAUNPUR' 'JHANSI' 'KANNAUJ' 'KANPUR DEHAT'
 'KANPUR NAGAR' 'KAUSHAMBI' 'KHERI' 'KUSHI NAGAR' 'LALITPUR' 'LUCKNOW'
 'MAHARAJGANJ' 'MAHOBA' 'MAINPURI' 'MATHURA' 'MAU' 'MEERUT' 'MIRZAPUR'
 'MORADABAD' 'MUZAFFARNAGAR' 'PILIBHIT' 'RAE BARELI' 'RAMPUR' 'SAHARANPUR'
 'SANT KABEER NAGAR' 'SANT RAVIDAS NAGAR' 'SHAHJAHANPUR' 'SHRAVASTI'
 'SIDDHARTH NAGAR' 'SITAPUR' 'SONBHADRA' 'SULTANPUR' 'UNNAO' 'VARANASI'
 'CHAMOLI' 'CHAMPAWAT' 'DEHRADUN' 'HARIDWAR' 'NAINITAL' 'PAURI GARHWAL'
 'PITHORAGARH' 'RUDRA PRAYAG' 'TEHRI GARHWAL' 'UDAM SINGH NAGAR'
 'UTTAR KASHI' 'ALMORA' 'BAGESHWAR' '24 PARAGANAS NORTH'
 '24 PARAGANAS SOUTH' 'BANKURA' 'BIRBHUM' 'COOCHBEHAR' 'DARJEELING'
 'DINAJPUR DAKSHIN' 'DINAJPUR UTTAR' 'HOOGHLY' 'HOWRAH' 'JALPAIGURI'
 'MALDAH' 'MEDINIPUR EAST' 'MEDINIPUR WEST' 'MURSHIDABAD' 'NADIA'
 'PURBA BARDHAMAN' 'PURULIA' 'ANJAW' 'BAKSA' 'CHIRANG' 'KAMRUP METRO'
 'UDALGURI' 'NARAYANPUR' 'NORTH GOA' 'SOUTH GOA' 'MEWAT' 'PALGHAR'
 'LAWNGTLAI' 'SERCHHIP' 'S' 'TARN TARAN' 'Andaman and Nicobar Islands'
 'DELHI_TOTAL' 'TAPI' 'PALWAL' 'REASI' 'SAMBA' 'KISHTWAR' 'RAMBAN'
 'KULGAM' 'BANDIPORA' 'GANDERBAL' 'SHOPIAN' 'KHUNTI' 'RAMGARH'
 'RAMANAGARA' 'CHIKBALLAPUR' 'ALIRAJPUR' 'SINGRAULI' 'KIPHIRE' 'LONGLENG'
 'PEREN' 'BARNALA' 'TIRUPPUR' 'ARIYALUR' 'KASGANJ' 'BALOD' 'BALODA BAZAR'
 'BEMETARA' 'GARIYABAND' 'KONDAGAON' 'MUNGELI' 'SUKMA' 'SURAJPUR' 'YADGIR'
 'FAZILKA' 'PATHANKOT' 'GOMATI' 'KHOWAI' 'SEPAHIJALA' 'UNAKOTI' 'AMETHI'
 'HAPUR' 'SAMBHAL' 'SHAMLI' 'KRA DAADI' 'LONGDING' 'NAMSAI' 'SIANG' 'DIU'
 'DAMAN' 'ARAVALLI' 'BOTAD' 'CHHOTAUDEPUR' 'GIR SOMNATH' 'MAHISAGAR'
 'DEVBHUMI DWARKA' 'MORBI' 'CHARKI DADRI' 'AGAR MALWA' 'NORTH GARO HILLS'
 'SOUTH WEST GARO HILLS' 'SOUTH WEST KHASI HILLS' 'WEST JAINTIA HILLS'
 'ALIPURDUAR' 'KAMLE' 'LOWER SIANG' 'MUMBAI SUBURBAN' 'CHENNAI'
 'BHADRADRI' 'JAGITIAL' 'JANGOAN' 'JAYASHANKAR' 'JOGULAMBA' 'KAMAREDDY'
 'KOMARAM BHEEM ASIFABAD' 'MAHABUBABAD' 'MANCHERIAL' 'MEDCHAL' 'MULUGU'
 'NAGARKURNOOL' 'NARAYANAPET' 'NIRMAL' 'PEDDAPALLI' 'RAJANNA' 'SANGAREDDY'
 'SIDDIPET' 'SURYAPET' 'VIKARABAD' 'WANAPARTHY' 'WARANGAL URBAN' 'YADADRI'
 'JHARGRAM' 'PASCHIM BARDHAMAN' 'KALIMPONG' 'LEPARADA' 'PAKKE KESSANG'
 'SHI YOMI' 'BISWANATH' 'CHARAIDEO' 'HOJAI' 'MAJULI'
 'SOUTH SALMARA MANCACHAR' 'WEST KARBI ANGLONG' 'GAURELLA-PENDRA-MARWAHI'
 'BAGALKOTE' 'BALLARI' 'BELAGAVI' 'CHAMARAJANAGARA' 'CHIKKABALLAPURA'
 'CHIKKAMAGALURU' 'DAKSHINA KANNADA' 'MYSURU' 'SHIVAMOGGA' 'TUMAKURU'
 'UTTARA KANNADA' 'VIJAYAPURA' 'KALABURAGI' 'YADAGIRI' 'NIWARI'
 'SHAHID BHAGAT SINGH NAGAR' 'TUTICORIN' 'KALLAKURICHI' 'TENKASI'
 'TIRUPATHUR' 'CHENGALPATTU' 'RANIPET' 'HANUMAKONDA' 'MEDCHAL MALKAJGIRI'
 'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU' 'HYDERABAD' 'MUMBAI']

In [ ]:
df['Area Units'].value_counts()

Area Units
Hectare    345407
Name: count, dtype: int64

In [ ]:
df['Production Units'].value_counts()

Production Units
Tonnes    331686
Bales      10794
Nuts        2927
Name: count, dtype: int64

In [ ]:
df[df['Production Units'] == 'Nuts']['Crop'].value_counts()

Crop
Coconut    2927
Name: count, dtype: int64

In [ ]:
def unit_standardization(df):
  if df['Production'] == 'Nuts':
    return np.round(df['Producton']/500,0)
  elif df['Production'] == 'Tonnes':
    return df['Production ']
  else:
    return np.round(df['Production']/4.59296,0)

In [ ]:
df['New Production']=df.apply(unit_standardization,axis=1)
df.sample(5)

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield,New Production
174954,Uttarakhand,DEHRADUN,Wheat,2010-11,Rabi,20956.0,Hectare,48703.0,Tonnes,2.324060,10604.0
113300,Nagaland,MON,Sugarcane,2009-10,Kharif,600.0,Hectare,18010.0,Tonnes,30.016667,3921.0
6128,Bihar,PASHCHIM CHAMPARAN,Jute,2001-02,Kharif,53.0,Hectare,354.0,Bales,6.679245,77.0
126345,Uttar Pradesh,KANPUR DEHAT,Sugarcane,2008-09,Kharif,2595.0,Hectare,116044.0,Tonnes,44.718304,25266.0
170826,Uttar Pradesh,GONDA,Moong(Green Gram),2011-12,Kharif,11.0,Hectare,5.0,Tonnes,0.454545,1.0

In [ ]:
df.drop(columns=['Production','Production Units','Area Units'])
df.head()

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield,New Production
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,Hectare,2061.0,Tonnes,1.643541,449.0
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.655803,454.0
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.209358,332.0
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.0,Hectare,5239.0,Tonnes,1.690000,1141.0
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.696296,1147.0

In [ ]:
#Which crop is most commen choice in India?

df['Crop'].value_counts().head()

Crop
Rice                 21611
Maize                20507
Moong(Green Gram)    15101
Urad                 14581
Sesamum              13049
Name: count, dtype: int64

In [ ]:
unique_states_list = df['State'].unique()
unique_states_list

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi',
       'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Telangana', 'Laddakh'], dtype=object)

# Get the statewise total crop Production

In [ ]:
total_production = []
for st in unique_states_list:
  total_production.append(df.loc[df['State'] == st,'New Production'].sum())

In [ ]:
crop_production_df=pd.DataFrame(
    {
        'State': unique_states_list,
        'Total Crop Production' : total_production
    }
)

In [ ]:
crop_production_df.sort_values('Total Crop Production',ascending=False).head(10)

                          State  Total Crop Production
17                       Kerala           2.823901e+10
29                   Tamil Nadu           1.699378e+10
16                    Karnataka           1.388490e+10
1                Andhra Pradesh           5.677432e+09
33                  West Bengal           1.946714e+09
31                Uttar Pradesh           9.672594e+08
3                         Assam           7.920196e+08
10                          Goa           4.776884e+08
0   Andaman and Nicobar Islands           4.470657e+08
19                  Maharashtra           4.090102e+08

##Which state is the highest producer of Maize between 1997 to 2022

In [ ]:
maize_df=df[df['Crop'] == 'Maize']

maize_states_list= maize_df['State'].unique()
unique_states_list

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi',
       'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Telangana', 'Laddakh'], dtype=object)

In [ ]:
total_maize_production = []
for st in maize_states_list:
  total_maize_production.append(maize_df.loc[maize_df['State']== st,'New Production'].sum())

In [ ]:
maize_production_df= pd.DataFrame(
    {
        'State': maize_states_list,
        'Total Crop Production': total_maize_production
    }
)

In [ ]:
maize_production_df.sort_values('Total Crop Production',ascending=False).head(10)

             State  Total Crop Production
14       Karnataka             15041045.0
0   Andhra Pradesh             12036925.0
3            Bihar             10617863.0
15  Madhya Pradesh             10079110.0
16     Maharashtra              7779820.0
23       Rajasthan              7202154.0
27   Uttar Pradesh              6592721.0
25      Tamil Nadu              5504289.0
32       Telangana              4121940.0
9          Gujarat              3286253.0

#Best Year for Agriculture

In [ ]:
df['Year'].unique()

array(['2001-02', '2002-03', '2003-04', '2004-05', '2005-06', '2006-07',
       '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13',
       '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19',
       '2019-20', '2020-21', '2000-01', '1997-98', '1998-99', '1999-00'],
      dtype=object)